from io import BytesIO

from datetime import datetime

from flask import send_file

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet

from reportlab.lib import colors

from models.attendance import Attendance


def generate_student_attendance_pdf(student):

    records = Attendance.query.filter_by(
        student_id=student.id
    ).all()

    present_days = Attendance.query.filter_by(
        student_id=student.id,
        status="Present"
    ).count()

    absent_days = Attendance.query.filter_by(
        student_id=student.id,
        status="Absent"
    ).count()

    total_days = len(records)

    percentage = 0

    if total_days > 0:

        percentage = round(
            (present_days / total_days) * 100,
            2
        )

    if percentage >= 75:

        attendance_status = "Good (Attendance ≥ 75%)"

    else:

        attendance_status = "Low Attendance (Attendance < 75%)"

    filename = (
        f"{student.roll_no}_Attendance_Report.pdf"
    )

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer
    )

    styles = getSampleStyleSheet()

    elements = []

    college = Paragraph(
        "Dhananjayrao Gadgil College of Commerce, Satara",
        styles["Title"]
    )

    title = Paragraph(
        "Student Attendance Report",
        styles["Heading2"]
    )

    generated = Paragraph(
        f"Generated On : {datetime.now().strftime('%d-%m-%Y %H:%M')}",
        styles["Normal"]
    )

    elements.append(college)
    elements.append(title)
    elements.append(generated)
    elements.append(
        Spacer(1, 15)
    )

    student_info = [

        ["Roll No", student.roll_no],

        ["Student Name", student.name],

        ["Course", student.course],

        ["Year", student.year]

    ]

    student_table = Table(student_info)

    student_table.setStyle(

        TableStyle([

            ("GRID", (0,0), (-1,-1), 1, colors.black),

            ("BACKGROUND", (0,0), (0,-1), colors.lightgrey),

            ("BOTTOMPADDING",(0,0),(-1,-1),8)

        ])

    )

    elements.append(student_table)

    elements.append(
        Spacer(1,15)
    )

    summary_title = Paragraph(
        "Attendance Summary",
        styles["Heading2"]
    )

    elements.append(summary_title)

    elements.append(
        Spacer(1,10)
    )

    summary_data = [

        ["Present Days", present_days],

        ["Absent Days", absent_days],

        ["Total Days", total_days],

        ["Attendance %", f"{percentage}%"],

        ["Status", attendance_status]

    ]

    summary_table = Table(summary_data)

    summary_table.setStyle(

        TableStyle([

            (
                "GRID",
                (0,0),
                (-1,-1),
                1,
                colors.black
            ),

            (
                "BACKGROUND",
                (0,0),
                (0,-1),
                colors.lightgrey
            ),

            (
                "BOTTOMPADDING",
                (0,0),
                (-1,-1),
                8
            )

        ])

    )

    elements.append(summary_table)

    elements.append(
        Spacer(1,15)
    )

    details_title = Paragraph(
        "Attendance Details",
        styles["Heading2"]
    )

    elements.append(details_title)

    elements.append(
        Spacer(1,10)
    )

    details_data = [[
        "Date",
        "Status"
    ]]

    for record in records:

        details_data.append([

            str(record.attendance_date),

            record.status

        ])

    details_table = Table(details_data)

    details_table.setStyle(

        TableStyle([

            (
                "BACKGROUND",
                (0,0),
                (-1,0),
                colors.HexColor("#0F172A")
            ),

            (
                "TEXTCOLOR",
                (0,0),
                (-1,0),
                colors.white
            ),

            (
                "FONTNAME",
                (0,0),
                (-1,0),
                "Helvetica-Bold"
            ),

            (
                "GRID",
                (0,0),
                (-1,-1),
                1,
                colors.black
            ),

            (
                "ROWBACKGROUNDS",
                (0,1),
                (-1,-1),
                [
                    colors.whitesmoke,
                    colors.lightgrey
                ]
            )

        ])

    )

    elements.append(details_table)

    elements.append(
        Spacer(1,20)
    )

    footer = Paragraph(
        "Generated by College Attendance Management System",
        styles["Italic"]
    )

    elements.append(footer)

    doc.build(elements)

    buffer.seek(0)

    return send_file(

        buffer,

        as_attachment=True,

        download_name=filename,

        mimetype="application/pdf"

    )